service: my-board-app

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: /{proxy+}
          method: ANY
    timeout: 30

plugins:
  - serverless-nextjs 